
package org.example.services.employeeService;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://services.web.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.services.employeeService.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmp", targetNamespace = "http://services.web.example.org/", className = "org.example.services.employeeService.AddEmp")
    @ResponseWrapper(localName = "addEmpResponse", targetNamespace = "http://services.web.example.org/", className = "org.example.services.employeeService.AddEmpResponse")
    @Action(input = "http://services.web.example.org/EmployeeService/addEmpRequest", output = "http://services.web.example.org/EmployeeService/addEmpResponse")
    public Employee addEmp(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.services.employeeService.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEmp", targetNamespace = "http://services.web.example.org/", className = "org.example.services.employeeService.DeleteEmp")
    @ResponseWrapper(localName = "deleteEmpResponse", targetNamespace = "http://services.web.example.org/", className = "org.example.services.employeeService.DeleteEmpResponse")
    @Action(input = "http://services.web.example.org/EmployeeService/deleteEmpRequest", output = "http://services.web.example.org/EmployeeService/deleteEmpResponse")
    public Employee deleteEmp(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.services.employeeService.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmp", targetNamespace = "http://services.web.example.org/", className = "org.example.services.employeeService.GetEmp")
    @ResponseWrapper(localName = "getEmpResponse", targetNamespace = "http://services.web.example.org/", className = "org.example.services.employeeService.GetEmpResponse")
    @Action(input = "http://services.web.example.org/EmployeeService/getEmpRequest", output = "http://services.web.example.org/EmployeeService/getEmpResponse")
    public Employee getEmp(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.example.services.employeeService.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEmp", targetNamespace = "http://services.web.example.org/", className = "org.example.services.employeeService.UpdateEmp")
    @ResponseWrapper(localName = "updateEmpResponse", targetNamespace = "http://services.web.example.org/", className = "org.example.services.employeeService.UpdateEmpResponse")
    @Action(input = "http://services.web.example.org/EmployeeService/updateEmpRequest", output = "http://services.web.example.org/EmployeeService/updateEmpResponse")
    public Employee updateEmp(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
